export const Routes = {
    login: '/auth/login',
    register: '/auth/register',
    admin: '/auth/admin',
    dashboard: '/dashboard',
    dashboardWallet: '/dashboard/',
    dashboardEditProfile: '/dashboard/edit-profile',
    dashboardAuthentication: '/dashboard/authentication',
    dashboardTransactions: '/dashboard/transactions',
    dashboardTickets: '/dashboard/tickets',
    adminDashboard: '/admin',
    adminDashboardCelebrity: '/admin/celebrity',
    adminDashboardFilm: '/admin/film',
    adminDashboardComment: '/admin/comment',
    adminDashboardReview: '/admin/review',
    adminDashboardReports: '/admin/reports',
    adminDashboardUsers: '/admin/users',
    adminDashboardSetting: '/admin/setting',
};
